config/routes.rb
Rails.application.routes.draw do

  match 'appointments/new_date' => 'appointments#new_date', :via => :get
  get 'customers/employee/:employee_id' => 'customers#employee', as: :customer_employee

  resources :secretaries do
    get 'appointments'
    get 'calendar'
    get 'expired_date'
  end
  resources :appointments do
    get 'accept'
  end
  resources :employees do
    get 'appointments', as: :appointment
    resources :appointments
    resources :working_hours
    get 'calendar'
  end
  resources :customers do
    get 'calendar'
    get 'search'
  end

  namespace :customers do
    resources :employee, only: :show
  end

  devise_for :users 
  root 'home#index'

  namespace :admin do
    resources :users do
      get 'user_list'
      get 'change_user_type',  as: :change_type
      get 'become'
    end
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
	belongs_to :user
	has_many :working_hours
	has_many :appointments

	validates :telephone_number, :position, presence: true
  	validates :telephone_number, length: {in: 9..12}
  	validates :telephone_number, numericality: { only_integer: true }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_employee
  before_action :set_user, except: [:show]

  def index
    @employee = @user.employee
  end

  def show
    if current_user.admin?
      @admin = current_user
      @employee = Employee.find(params[:id])
      @user = User.find(@employee.user_id)
    else
      redirect_to root_path, notice: "You're not admin"
    end
  end


  def new
    @employee = @user.build_employee
  end

  def edit
    @employee = @user.employee
  end

  def create
    @employee = @user.build_employee(employee_params)
    if @employee.save
      redirect_to root_path, notice: 'Created'
    else
      render :new
    end
  end


  def update
    @employee = @user.employee
    if @employee.update(employee_params)
      redirect_to root_path, notice: 'Updated'
    else
      render :edit
    end
  end


  def destroy
    
  end

  def appointments
    @employee = @user.employee
    @appointments = Appointment.all.includes(:customer).where(employee_id: @employee.id)
  end

  def calendar
    @employee = @user.employee
    @appointments = Appointment.where(employee_id: @employee.id)
    @merged_date = {"id" => "date"}
    @appointments.each do |appointment|
      @merged_date[appointment.id] = "#{appointment.appointment_date}T#{appointment.appointment_time}:00"
    end
  end


  private
    def set_employee
    end

    def set_user
      @user = current_user
    end

    def authenticate_employee
      redirect_to root_path, notice: "You're not employee" unless current_user.employee? || current_user.admin?
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :telephone_number, 
        :position)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for @employee do |f| %>
<div class="panel-body">
  <div class="form-group">
    <%= f.label :telephone_number %><br>
    <%= f.text_field :telephone_number %>
  </div>
  <div class="form-group">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="actions">
    <%= f.submit @employee.persisted? ? "Update" : "Finish", class: "btn btn-primary" %>
  </div>
</div>

<% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/employees/appointments.html.erb
<main>
  <div class="panel panel-default">
  <div class="panel-heading">Appointments</div>
    <div class="panel-body">

    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Purpose</th>
          <th>Date</th>
          <th>Time</th>
          <th>Customer</th>
          <th>Confirmed</th>
        </tr>
      </thead>

      <tbody>
          <% @appointments.order(:appointment_date).each do |appointment| %>
              <tr>
                <td><%= appointment.purpose %></td>
                <td><%= appointment.appointment_date %></td>
                <td><%= appointment.appointment_time %></td>
                <td><%= appointment.customer.first_name %>  <%= appointment.customer.last_name %></td>
                <td><%= appointment.confirmation ? 'Yes' : 'No' %></td>
              </tr>
          <% end %>
      </tbody>
    </table>
    <%= link_to 'Calendar', employee_calendar_path(@employee), class: "btn btn-primary" %>
  </div>
  <div class="panel-footer">
    <%= link_to "Main page", root_path %>
  </div>
</div>
</main>

app/views/employees/calendar.html.erb
<main>
	<div class="calendar" data-path="<%= employee_calendar_path(@employee) %>"></div>
	<div class="panel-footer">
    <%= link_to "Main page", root_path %>||<%= link_to "Back", employee_appointment_path(@employee) %>
  </div>
</main>

app/views/employees/edit.html.erb
<main>
	<div class="panel panel-default">
		<div class="panel-heading">Edit profile</div>

	<%= render 'form' %>

	<div class="panel-footer"><%= link_to 'Back', root_path %></div>
	</div>
</main>

app/views/employees/index.html.erb
<main class="center">
  <% if @user.try(:employee) && @user.employee? %>
    <%= link_to 'Edit profile', edit_employee_path(@employee), class: "btn btn-primary" %>
    <%= link_to 'Working hours', employee_working_hours_path(@employee), class: "btn btn-primary" %>
    <%= link_to 'Your appointments',employee_appointment_path(@employee), class: "btn btn-primary" %>
  <% elsif @user.employee? %>
    <%= link_to 'Finish profile', new_employee_path, class: "btn btn-primary" %>
  <%end%>
  <%= link_to 'Edit account', edit_user_registration_path, class: "btn btn-primary" %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
</main>

app/views/employees/new.html.erb
<main>	
	<div class="panel panel-default">
		<div class="panel-heading">Finish profile</div>

	<%= render 'form' %>

	<div class="panel-footer"><%= link_to 'Back', root_path %></div>
	</div>
</main>

app/views/employees/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Employee <%= first_name?(@employee) %> <%= last_name?(@employee) %></div>
  <div class="panel-body">
  <b>First name:</b> <%= @user.first_name %> </br>
  <b>To:</b> <%= @user.last_name %> </br>
  <b>E-mail:</b> <%= @user.email %> </br>
  <b>Telephone number:</b> <%= @employee.telephone_number %> </br>
  <b>Position:</b> <%= @employee.position %> </br>
  <%= link_to 'Back', admin_user_user_list_path(@admin) %>
  </div>
</div>