config/routes.rb
Rails.application.routes.draw do

  match 'appointments/new_date' => 'appointments#new_date', :via => :get
  get 'customers/employee/:employee_id' => 'customers#employee', as: :customer_employee

  resources :secretaries do
    get 'appointments'
    get 'calendar'
    get 'expired_date'
  end
  resources :appointments do
    get 'accept'
  end
  resources :employees do
    get 'appointments', as: :appointment
    resources :appointments
    resources :working_hours
    get 'calendar'
  end
  resources :customers do
    get 'calendar'
    get 'search'
  end

  namespace :customers do
    resources :employee, only: :show
  end

  devise_for :users 
  root 'home#index'

  namespace :admin do
    resources :users do
      get 'user_list'
      get 'change_user_type',  as: :change_type
      get 'become'
    end
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	belongs_to :user
	has_many :appointments

	validates :telephone_number, 
        :city, :pesel, presence: true
  validates :telephone_number, length: {in: 9..12}
  validates :pesel, length: {is: 11}
  validates :telephone_number, :pesel, numericality: { only_integer: true }

	def customer_fields
		[first_name, last_name, telephone_number, city, pesel]
	end

	def all_filled?
		customer_fields.compact.size >= customer_fields.size
	end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer
  before_action :set_user, except: [:show]

  def index
    @customer = @user.customer
  end

  def show
    if current_user.admin?
      @admin = current_user
      @customer = Customer.find(params[:id])
      @user = User.find(@customer.user_id)
    else
      redirect_to root_path, notice: "You're not admin"
    end
  end

  def new
    @customer = @user.build_customer
  end

  def edit
    @customer = @user.customer
  end

  def create
    @customer = @user.build_customer(customer_params)
    if @customer.save
      redirect_to root_path, notice: 'Created'
    else
      render :new
    end
  end

  def update
    @customer = @user.customer
    if @customer.update(customer_params)
      redirect_to root_path, notice: 'Updated'
    else
      render :edit
    end
  end

  def destroy
  end

  def search
    @employee = Employee.all
    @customer = @user.customer
  end

  def calendar
    @customer = @user.customer
    @appointments = Appointment.where(customer_id: @customer.id)
    @merged_date = {"id" => "date"}
    @appointments.each do |appointment|
      @merged_date[appointment.id] = "#{appointment.appointment_date}T#{appointment.appointment_time}:00"
    end
  end

  def employee
    @employee = Employee.find(params[:employee_id])
    @working_hours = @employee.working_hours
    @appointments = Appointment.where(employee_id: @employee.id).where(confirmation: true)
    @merged_date = {"id" => "date"}
    @appointments.each do |appointment|
      @merged_date[appointment.id] = "#{appointment.appointment_date}T#{appointment.appointment_time}:00"
    end
  end

  private
    def set_customer
    end

    def set_user
      @user = current_user
    end

    def authenticate_customer
      redirect_to root_path, notice: "You're not customer" unless current_user.customer? || current_user.admin?
    end

    def customer_params
      params.require(:customer).permit(:telephone_number, :city, :pesel)
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/customer_helper.rb
module CustomerHelper

	def employee_first_name(employee)
		return User.find(employee.user_id).first_name
	end

	def employee_last_name(employee)
		return User.find(employee.user_id).last_name
	end
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>
<div class="panel-body">
  <div class="form-group">
    <%= f.label :telephone_number %><br>
    <%= f.text_field :telephone_number %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="form-group">
    <%= f.label :pesel %><br>
    <%= f.text_field :pesel %>
  </div>
  <div class="actions">
    <%= f.submit @customer.persisted? ? "Update" : "Finish", class: "btn btn-primary" %>
  </div>
</div>

<% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this bot from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/customers/calendar.html.erb
<main>
	<div class="calendar" data-path="<%= customer_calendar_path(@customer) %>"></div>
	<div class="panel-footer">
    <%= link_to "Main page", root_path %>||<%= link_to "Back", appointments_path %>
  </div>
</main>

app/views/customers/edit.html.erb
<main>
	<div class="panel panel-default">
		<div class="panel-heading">Edit profile</div>

	<%= render 'form' %>

	<div class="panel-footer"><%= link_to 'Back', root_path %></div>
	</div>
</main>

app/views/customers/employee.html.erb
<main>
	<div class="panel panel-default">
  <div class="panel-heading">Listing working hours for <%= @employee.first_name%> <%= @employee.last_name%></div>
  <div class="panel-body">

    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Day</th>
          <th>Start</th>
          <th>End</th>

        </tr>
      </thead>

      <tbody>
        <% @working_hours.order(:lp).each do |hour| %>
          <tr>
            <td><%= hour.day.capitalize%></td>
            <td><%= hour.start_hour%></td>
            <td><%= hour.end_hour%></td>
           
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Make appointment", appointments_new_date_path(employee: @employee.id), class: "btn btn-primary" %>
    <div class="calendar" data-path="<%= customer_employee_path(@employee, format: :json) %>"></div>
  </div>
  <div class="panel-footer">
    <%= link_to "Main page", root_path %>||<%= link_to "Back", customer_search_path(@user.customer)  %>
  </div>
</div>
</main>

app/views/customers/index.html.erb
<main class="center">
	<% if @user.try(:customer) && @user.customer? %>
		<%= link_to 'Edit profile', edit_customer_path(@customer), class: "btn btn-primary" %>
		<%= link_to 'Search employee', customer_search_path(@customer), class: "btn btn-primary"%>
		<%= link_to 'View yours appointments', appointments_path, class: "btn btn-primary"%>
	<% elsif @user.customer? %>
		<%= link_to 'Finish profile', new_customer_path, class: "btn btn-primary" %>
	<% end %>
	<%= link_to 'Edit account', edit_user_registration_path, class: "btn btn-primary" %>
	<%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
</main>

app/views/customers/new.html.erb
<main>	
	<div class="panel panel-default">
		<div class="panel-heading">Finish profile</div>

	<%= render 'form' %>

	<div class="panel-footer"><%= link_to 'Back', root_path %></div>
	</div>
</main>

app/views/customers/search.html.erb
<main>
	<div class="panel panel-default">
  <div class="panel-heading">Listing employees</div>
  <div class="panel-body">

    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>First name</th>
          <th>Last Name</th>
          <th>Position</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @employee.order(:position).each do |employee| %>
          <tr>
            <td><%= employee_first_name(employee)%></td>
            <td><%= employee_last_name(employee)%></td>
            <td><%= employee.position %></td>
            <td><%= link_to "Show working hours", customer_employee_path(employee), class: "btn btn-primary" %></td>
            <td><%= link_to "Make appointment", appointments_new_date_path(employee: employee.id), class: "btn btn-primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="panel-footer">
    <%= link_to "Main page", root_path %>||<%= link_to 'Back', customers_path %>
  </div>
</div>
</main>

app/views/customers/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Customer <%= first_name?(@customer) %> <%= last_name?(@customer) %></div>
  <div class="panel-body">
  <b>First name:</b> <%= @user.first_name %> </br>
  <b>To:</b> <%= @user.last_name %> </br>
  <b>E-mail:</b> <%= @user.email %> </br>
  <b>Telephone number:</b> <%= @customer.telephone_number %> </br>
  <b>City:</b> <%= @customer.city %> </br>
  <b>Pesel:</b> <%= @customer.pesel %> </br>
  <%= link_to 'Back', admin_user_user_list_path(@admin) %>
  </div>
</div>