config/routes.rb
Rails.application.routes.draw do

  match 'appointments/new_date' => 'appointments#new_date', :via => :get
  get 'customers/employee/:employee_id' => 'customers#employee', as: :customer_employee

  resources :secretaries do
    get 'appointments'
    get 'calendar'
    get 'expired_date'
  end
  resources :appointments do
    get 'accept'
  end
  resources :employees do
    get 'appointments', as: :appointment
    resources :appointments
    resources :working_hours
    get 'calendar'
  end
  resources :customers do
    get 'calendar'
    get 'search'
  end

  namespace :customers do
    resources :employee, only: :show
  end

  devise_for :users 
  root 'home#index'

  namespace :admin do
    resources :users do
      get 'user_list'
      get 'change_user_type',  as: :change_type
      get 'become'
    end
  end

end

app/models/secretary.rb
class Secretary < ActiveRecord::Base
	belongs_to :user

	validates :telephone_number, presence: true
	validates :telephone_number, length: {in: 9..12}
  	validates :telephone_number, numericality: { only_integer: true }
end

app/controllers/secretaries_controller.rb
class SecretariesController < ApplicationController
  before_action :set_secretary, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_secretary

  def index
    @user = current_user
    @secretary = @user.secretary
  end


  def show
    if current_user.admin?
      @admin = current_user
      @secretary = Secretary.find(params[:id])
      @user = User.find(@secretary.user_id)
    else
      redirect_to root_path, notice: "You're not admin"
    end
  end

 
  def new
    @secretary = current_user.build_secretary
  end

  def edit
    @secretary = current_user.secretary
  end


  def create
    @secretary = current_user.build_secretary(secretary_params)
    if @secretary.save
      redirect_to root_path, notice: "Created"
    else
      render :new
    end
  end

  
  def update
    @secretary = current_user.secretary
    if @secretary.update(secretary_params)
      redirect_to root_path, notice: "Updated"
    else
      render :edit
    end
  end

  
  def destroy
    
  end

  def appointments
    @status = params[:status]
    @secretary = current_user.secretary
    @appointments = Appointment.where(confirmation: view_context.wait_or_confirmed?(@status))
    @employee_name = {"appid" => "fullname"}
    @customer_name = {"appid" => "fullname"}
    @appointments.each do |appointment|
      @employee = User.find(Employee.find(appointment.employee_id).user_id)
      @customer = User.find(Customer.find(appointment.customer_id).user_id)
      @employee_name[appointment.id] = "#{@employee.first_name} #{@employee.last_name}"
      @customer_name[appointment.id] = "#{@customer.first_name} #{@customer.last_name}"
    end
  end

  def calendar
    @status = params[:status]
    @secretary = current_user.secretary
    @appointments = Appointment.where(confirmation: view_context.wait_or_confirmed?(@status))
    @merged_date = {"id" => "date"}
    @appointments.each do |appointment|
      @merged_date[appointment.id] = "#{appointment.appointment_date}T#{appointment.appointment_time}:00"
    end
  end

  def expired_date
    @appointments = Appointment.all
    @deleted = false
    unless @appointments.empty?
      @appointments.each do |appointment|
        if appointment.appointment_date < Date.today
          appointment.destroy
          @customer = Customer.find(appointment.customer_id)
          UserMailer.declined_appointment(@customer, appointment).deliver_now
          @deleted = true
        end
      end
    end
    redirect_to root_path, notice: @deleted ? "All expired appointments has beed deleted" : "There was no expired appointments"
  end

  private
    def set_secretary

    end

    def authenticate_secretary
      redirect_to root_path, notice: "You're not secretary" unless current_user.secretary? || current_user.admin?
    end
  
    def secretary_params
      params.require(:secretary).permit(:first_name, :last_name, :telephone_number)
    end
end

app/helpers/secretaries_helper.rb
module SecretariesHelper
end

app/views/secretaries/_form.html.erb
<%= form_for @secretary do |f| %>
<div class="panel-body">
  <div class="form-group">
    <%= f.label :telephone_number %><br>
    <%= f.text_field :telephone_number %>
  </div>
  <div class="actions">
    <%= f.submit @secretary.persisted? ? "Update" : "Finish", class: "btn btn-primary" %>
  </div>
</div>

<% if @secretary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@secretary.errors.count, "error") %> prohibited this secretary from being saved:</h2>

      <ul>
      <% @secretary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/secretaries/appointments.erb
<main>
  <div class="panel panel-default">
  <div class="panel-heading"><%= @status %> appointments</div>
    <div class="panel-body">

    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Purpose</th>
          <th>Date</th>
          <th>Time</th>
          <th>Employee</th>
          <th>Customer</th>
          <th colspan="1"></th>
        </tr>
      </thead>

      <tbody>
          <% @appointments.order(:appointment_date, :appointment_time, :purpose).each do |appointment| %>
            <tr>
              <td><%= appointment.purpose %></td>
              <td><%= appointment.appointment_date %></td>
              <td><%= appointment.appointment_time %></td>
              <td><%= @employee_name[appointment.id] %></td>
              <td><%= @customer_name[appointment.id]%></td>
              <td><%= link_to 'Show', appointment_path(appointment, status: @status), class: "btn btn-primary" %></td>
            </tr>
          <% end %>
      </tbody>
    </table>
    <%= link_to 'Calendar', secretary_calendar_path(@secretary, status: @status), class: "btn btn-primary" %>
  </div>
  <div class="panel-footer">
    <%= link_to "Main page", root_path %>
  </div>
</div>
</main>

app/views/secretaries/calendar.html.erb
<main>
	<div class="calendar" data-path="<%= secretary_calendar_path(@secretary, status: @status) %>"></div>
	<div class="panel-footer">
    <%= link_to "Main page", root_path %>||<%= link_to "Back", secretary_appointments_path(@secretary, status: @status) %>
  </div>
</main>

app/views/secretaries/edit.html.erb
<main>
	<div class="panel panel-default">
		<div class="panel-heading">Edit profile</div>

	<%= render 'form' %>

	<div class="panel-footer"><%= link_to 'Back', root_path %></div>
	</div>
</main>

app/views/secretaries/index.html.erb
<main class="center">
  <% if @user.try(:secretary) && @user.secretary? %>
    <%= link_to 'Edit profile', edit_secretary_path(@secretary), class: "btn btn-primary" %>
    <%= link_to 'Waiting appointments', secretary_appointments_path(@secretary, status: "Waiting"), class: "btn btn-primary" %>
    <%= link_to 'Confirmed appointments', secretary_appointments_path(@secretary, status: "Confirmed"), class: "btn btn-primary" %>
    <%= link_to 'Expired appointments', secretary_expired_date_path(@secretary), class: "btn btn-primary" %>
  <% elsif @user.secretary? %>
    <%= link_to 'Finish profile', new_secretary_path, class: "btn btn-primary" %>
  <% end %>
  <%= link_to 'Edit account', edit_user_registration_path, class: "btn btn-primary" %>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
</main>

app/views/secretaries/new.html.erb
<main>	
	<div class="panel panel-default">
		<div class="panel-heading">Finish profile</div>

	<%= render 'form' %>

	<div class="panel-footer"><%= link_to 'Back', root_path %></div>
	</div>
</main>

app/views/secretaries/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Secretary <%= first_name?(@secretary) %> <%= last_name?(@secretary) %></div>
  <div class="panel-body">
  <b>First name:</b> <%= first_name?(@secretary) %> </br>
  <b>To:</b> <%= last_name?(@secretary) %> </br>
  <b>E-mail:</b> <%= @user.email %> </br>
  <b>Telephone number:</b> <%= @secretary.telephone_number %> </br>
  <%= link_to 'Back', admin_user_user_list_path(@admin) %>
  </div>
</div>