config/routes.rb
Rails.application.routes.draw do

  match 'appointments/new_date' => 'appointments#new_date', :via => :get
  get 'customers/employee/:employee_id' => 'customers#employee', as: :customer_employee

  resources :secretaries do
    get 'appointments'
    get 'calendar'
    get 'expired_date'
  end
  resources :appointments do
    get 'accept'
  end
  resources :employees do
    get 'appointments', as: :appointment
    resources :appointments
    resources :working_hours
    get 'calendar'
  end
  resources :customers do
    get 'calendar'
    get 'search'
  end

  namespace :customers do
    resources :employee, only: :show
  end

  devise_for :users 
  root 'home#index'

  namespace :admin do
    resources :users do
      get 'user_list'
      get 'change_user_type',  as: :change_type
      get 'become'
    end
  end

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :user
	belongs_to :employee
	belongs_to :customer

	validates :purpose, :extra, :appointment_date, :appointment_time, presence: true
	#validates :appointment_time, uniqueness: {scope: [:employee_id, :appointment_date] }
	validate :already_confirmed

	private

		def already_confirmed
			other_appointments = Appointment.where(
	                             appointment_date: self.appointment_date,
	                             appointment_time: self.appointment_time,
	                             employee_id: self.employee_id,
	                             confirmation: true
	                           ) 
	      unless other_appointments.empty?
	        [:appointment_date].each do |attr|
	          errors.add(attr,"is not available")
	        end
	      end       
	    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  
  def index
   @customer = @user.customer
   @appointments = @user.appointments.paginate(:page => params[:page],:per_page => 1)
   @employee_name = {"appid" => "fullname"}
   @appointments.each do |appointment|
      @employee = User.find(Employee.find(appointment.employee_id).user_id)
      @employee_name[appointment.id] = "#{@employee.first_name} #{@employee.last_name}"
    end
  end


  def show
    @appointment = Appointment.all.find(params[:id])
    @secretary = current_user.secretary
    @customer = Customer.find(@appointment.customer_id)
    @employee = Employee.find(@appointment.employee_id)
    @status = params[:status]
    @customer_user = User.find(@customer.user_id)
    @employee_user = User.find(@employee.user_id)
  end

  def new_date
    @employee = Employee.find(params[:employee])
    @customer = @user.customer
    @appointment = @user.appointments.build
  end


  def new
    @employee = Employee.find(params[:employee_id])
    @customer = @user.customer
    @appointment = @user.appointments.build(appointment_date_params)
    if @appointment.appointment_date.nil? || @appointment.appointment_date.sunday? || @appointment.appointment_date.saturday? || @appointment.appointment_date < Date.today 
      redirect_to appointments_new_date_path(employee: @employee.id), alert: "Wrong date" and return
    end
    set_hours(@appointment, @employee)
  end


  def edit
    @appointment = @user.appointments.find(params[:id])
    @employee = Employee.find(params[:employee_id])
    set_hours(@appointment, @employee)
  end

  
  def create
    @customer = @user.customer
    @employee = Employee.find(params[:employee_id])
    @employee_appointments = Appointment.where(employee_id: @employee.id)
    @appointment = @user.appointments.build(appointment_params)
    set_hours(@appointment, @employee)
    @employee_appointments = @employee_appointments.where(appointment_date: @appointment.appointment_date)
    @appointment.customer_id = @customer.id
    @appointment.employee_id = @employee.id
    if @appointment.save
      redirect_to root_path, notice: 'Appointment made, wait for acceptance'
    else
      render :new
    end
  end

  def update
    @employee = Employee.find(params[:employee])
    @appointment = @user.appointments.find(params[:id])
    set_hours(@appointment, @employee)
    if @appointment.update(appointment_params)
      redirect_to appointments_path, notice: 'Appointment updated'
    else
      render :edit
    end
  end


  def destroy
    @status = params[:status]
    @appointment = Appointment.find(params[:id])
    @customer = Customer.find(@appointment.customer_id)
    @secretary = @user.secretary
    @appointment.destroy
    if @user.secretary?
      UserMailer.declined_appointment(@customer, @appointment).deliver_now
      redirect_to secretary_appointments_path(@secretary, status: @status)
    elsif @user.customer?
      redirect_to appointments_path
    end
  end

  def accept
    @secretary = @user.secretary
    @status = params[:status]
    @appointment = Appointment.find(params[:appointment_id])
    @customer = Customer.find(@appointment.customer_id)
    @appointment.confirmation = true
    if @appointment.save
      UserMailer.accepted_appointment(@customer, @appointment).deliver_now
      appointments_with_same_date(@appointment)
      redirect_to secretary_appointments_path(@secretary, status: @status), notice: "Appointment confirmed"
    else
      redirect_to secretary_appointments_path(@secretary, status: @status), notice: "Error occured"
    end
  end

  private
   
    def set_appointment
      
    end

    def set_user
      @user = current_user
    end

    def appointments_with_same_date(appointment)
      @appointments = Appointment.where(appointment_date: appointment.appointment_date)
                                  .where(appointment_time: appointment.appointment_time)
                                  .where(employee_id: appointment.employee_id)
                                  .where(confirmation: false)
      unless @appointments.empty?
        @appointments.each do |appointment|
          appointment.destroy
          @customer = Customer.find(appointment.customer_id)
          UserMailer.declined_appointment(@customer, appointment).deliver_now
        end
      end     
    end

    def set_hours(appointment, employee)
      @select_hours = Array.new
      @working_hours = employee.working_hours.where(lp: appointment.appointment_date.wday).take
      @hours = @working_hours.end_hour[0..1].to_f - @working_hours.start_hour[0..1].to_f
      if(@hours == 1) 
        @hours = @hours - 1 
      end
      for i in 0..@hours
        @select_hours.push("#{sprintf('%g', @working_hours.start_hour[0..1].to_f+i)}:00") unless (@working_hours.start_hour[3..4] == '30' && i == 0)
        @select_hours.push("#{sprintf('%g', @working_hours.start_hour[0..1].to_f+i)}:30") unless (@working_hours).end_hour[3..4] != '30' && i == @hours
      end
    end
   
    def appointment_params
      params.require(:appointment).permit(:purpose, :extra, :appointment_date, :appointment_time)
    end

    def appointment_date_params
      params.require(:appointment).permit(:appointment_date)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper

	def wait_or_confirmed?(value)
		if value == "Waiting"
			false
		elsif value == "Confirmed"
			true
		end
	end

	def go_back(user, status)
		if user.customer?
			appointments_path
		elsif user.employee?
			employee_calendar_path(user.employee)
		elsif user.secretary?
			secretary_calendar_path(user.secretary, status)
		elsif user.admin?
			admin_user_user_list_path(user)		
		end
	end

end

app/views/appointments/_form.html.erb
<%= form_for @appointment, url: (@appointment.new_record? ? employee_appointments_path(@employee) : appointment_path(@appointment, employee: @employee.id)), method: (@appointment.new_record? ? :post : :put) do |f| %>
<div class="panel-body">
  <div class="form-group">
    <%= f.label :purpose, "Purpose of the appointment" %><br>
    <%= f.text_field :purpose, size: 40 %>
  </div>
  <div class="form-group">
    <%= f.label :extra, "Extra informations" %><br>
    <%= f.text_field :extra, size: 65 %>
  </div>
  <div class="form-group">
    <%= f.label :appointment_time, "Appointment time" %><br>
    <%= f.select :appointment_time, @select_hours.map { |value| [value, value] }  %>
  </div>
  <div class="form-group">
    <%= f.label :appointment_date, "Appointment date" %><br>
    <%= f.date_field :appointment_date, :readonly => true %>
  </div>
  
  <div class="actions">
    <%= f.submit @appointment.persisted? ? "Update" : "Finish", class: "btn btn-primary" %>
  </div>
</div>

<% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/appointments/edit.html.erb
<main>	
	<div class="row">
		<div class="column left">
			<div class="panel panel-default">
				<div class="panel-heading">Edit appointment</div>

					<%= render 'form' %>

				<div class="panel-footer"><%= link_to 'Back', appointments_path %></div>
			</div>
		</div>
		<div class="column right">
			<main>
			  	<div class="panel panel-default">
			  	<div class="panel-heading">Working hours</div>
				  	<div class="panel-body">

				    <table class="table table-hover table-condensed">
				      <thead>
				        <tr>
				          <th>Day</th>
				          <th>Open</th>
				          <th>Close</th>
				        </tr>
				      </thead>

				      <tbody>
				          <% unless @employee.working_hours.blank? %>
				          <% @employee.working_hours.order(:lp).each do |hour| %>
				            <tr>
				              <td><%= hour.day.capitalize %></td>
				              <td><%= hour.start_hour %></td>
				              <td><%= hour.end_hour %></td>
				            </tr>
				          <% end %>
				        <% end %>
				      </tbody>
				    </table>
				  </div>
				</div>
			</main>
		</div>
	</div>
</main>

app/views/appointments/index.html.erb
<main>
  <div class="panel panel-default">
  <div class="panel-heading">Your appointments</div>
    <div class="panel-body">

    <table class="table table-hover table-condensed">
      <thead>
        <tr>
          <th>Purpose</th>
          <th>Extra</th>
          <th>Date</th>
          <th>Time</th>
          <th>Employee</th>
          <th>Confirmed</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
          <% @appointments.order(:appointment_date, :appointment_time, :purpose).each do |appointment| %>
            <tr>
              <td><%= appointment.purpose %></td>
              <td><%= appointment.extra %></td>
              <td><%= appointment.appointment_date %></td>
              <td><%= appointment.appointment_time %></td>
              <td><%= @employee_name[appointment.id] %></td>
              <td>
                <%if appointment.confirmation%>
                  Yes
                <%else%>
                  No
                <%end%>
              </td>
              <td><%= link_to 'Edit', edit_employee_appointment_path(appointment.employee_id, appointment), class: "btn btn-primary" %></td>
              <td><%= link_to 'Show', appointment_path(appointment.id), class: "btn btn-primary" %></td>
              <td><%= link_to "Cancel", appointment_path(appointment), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-primary" %></td>
            </tr>
          <% end %>
      </tbody>
    </table>
    <%= link_to 'New appointment', customer_search_path(@customer), class: "btn btn-primary" %>
    <%= link_to 'Calendar', customer_calendar_path(@customer), class: "btn btn-primary" %>
  </div>
  <div class="panel-footer">
    <%= link_to "Main page", root_path %>
  </div>
</div>
<%= will_paginate @appointments %>
</main>

app/views/appointments/new.html.erb
<main>	
	<div class="row">
		<div class="column left">
			<div class="panel panel-default">
				<div class="panel-heading">Make appointment <%= @hours %></div>

				<%= render 'form' %>

				<div class="panel-footer"><%= link_to 'Back', customer_search_path(@customer) %></div>
			</div>
		</div>
		<div class="column right">
			<main>
			  	<div class="panel panel-default">
			  	<div class="panel-heading">Working hours</div>
				  	<div class="panel-body">

				    <table class="table table-hover table-condensed">
				      <thead>
				        <tr>
				          <th>Day</th>
				          <th>Open</th>
				          <th>Close</th>
				        </tr>
				      </thead>

				      <tbody>
				          <% unless @employee.working_hours.blank? %>
				          <% @employee.working_hours.order(:lp).each do |hour| %>
				            <tr>
				              <td><%= hour.day.capitalize %></td>
				              <td><%= hour.start_hour %></td>
				              <td><%= hour.end_hour %></td>
				            </tr>
				          <% end %>
				        <% end %>
				      </tbody>
				    </table>
				  </div>
				</div>
			</main>
		</div>
	</div>
</main>

app/views/appointments/new_date.erb
<main>	
	<div class="panel panel-default">
		<div class="panel-heading">Choose date</div>

		<%= form_for @appointment, url: new_employee_appointment_path(@employee, @appointment), method: :get do |f| %>
			  <div class="form-group">
			    <%= f.label :appointment_date, "Appointment date" %><br>
			    <%= f.date_field :appointment_date %>
			  </div>
			  <div class="actions">
			    <%= f.submit @appointment.persisted? ? "Update" : "Next", class: "btn btn-primary" %>
			  </div>
			</div>

			<% if @appointment.errors.any? %>
			    <div id="error_explanation">
			      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this bot from being saved:</h2>
			      <ul>
			      <% @appointment.errors.full_messages.each do |message| %>
			        <li><%= message %></li>
			      <% end %>
			      </ul>
			    </div>
			<% end %>
		<% end %>


	<div class="panel-footer"><%= link_to 'Back', root_path %></div>
	</div>
</main>

app/views/appointments/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Appointment</div>
  <div class="panel-body">
  <b>From:</b> <%= @customer_user.first_name %> <%= @customer_user.last_name %> </br>
  <b>To:</b> <%= @employee_user.first_name %> <%= @employee_user.last_name %> </br>
  <b>Purpose:</b> <%= @appointment.purpose %> </br>
  <b>Extra information:</b> <%= @appointment.extra %> </br>
  <b>Date:</b> <%= @appointment.appointment_date %> </br>
  <b>Time:</b> <%= @appointment.appointment_time %> </br>
  <% if !@appointment.confirmation && (current_user.secretary? || current_user.admin? || current_user.employee? ) %>
    <%= link_to 'Accept', appointment_accept_path(@appointment, status: @status),data: { confirm: "Are you sure?" } , class: "btn btn-primary" %>
  <% end %>
  <%= link_to 'Decline', appointment_path(@appointment, status: @status), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-primary" %>
  </br>
  <%= link_to 'Back', go_back(current_user, @status) %>
  </div>
</div>